const ALGORAND_TESTNET_CAIP2 =
  "algorand:SGO1GKSzyE7IEPItTxCByw9x8FmnrCDe";

const USDC_TESTNET_ASA_ID = 10458941;

const RECEIVER_ADDRESS =
  "VQF5PIPVPWL23YPIJHCDTFB6FWLTHRN4GW7FDKLTCGBE4FINYD4TE5O2E4";

const FACILITATOR_URL =
  "https://facilitator.goplausible.xyz";

module.exports = {
  ALGORAND_TESTNET_CAIP2,
  USDC_TESTNET_ASA_ID,
  RECEIVER_ADDRESS,
  FACILITATOR_URL,
};